import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@/styles/custom.css";
import { iransansFonts } from "./theme/localFont";
import { GlobalContextProvider } from "@/context/store";
import ResponsiveAppBar from "@/components/BasUIComponents/ResponsiveAppBar";
import ResponsiveFooter from "@/components/BasUIComponents/ResponsiveFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl" className={`${iransansFonts.variable} font-sans`}>
      <body className={`${iransansFonts.variable} font-sans`}>
        <GlobalContextProvider>
          <div className="flex flex-col min-h-screen">
            <ResponsiveAppBar />
            <div className="flex-grow w-full bg-main relative">{children}</div>
            <ResponsiveFooter />
          </div>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
