// "use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@/styles/custom.css";
import { iransansFonts } from "./theme/localFont";
import { GlobalContextProvider } from "@/context/store";
import ErrorBoundaryComponent from "@/components/global/error-boundary/ErrorBoundaryComponent";
import { ErrorBoundary } from "react-error-boundary";
import { useEffect, useState } from "react";

export const metadata: Metadata = {
  title: "بلیط هواپیما - خرید بلیط هواپیما",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl" className={`${iransansFonts.variable} font-sans`}>
      <body className={`${iransansFonts.variable} font-sans`}>
        <GlobalContextProvider>{children}</GlobalContextProvider>
      </body>
    </html>
  );
}
