import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@/styles/custom.css";
import { GlobalContextProvider } from "@/context/store";
import ErrorBoundaryComponent from "@/components/global/error-boundary/ErrorBoundaryComponent";
import { ErrorBoundary } from "react-error-boundary";
import { useEffect, useState } from "react";
import { iranyekanxFonts } from "./theme/localFont";

export const metadata: Metadata = {
  title: "بلیط هواپیما - خرید بلیط هواپیما",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      dir="rtl"
      className={`${iranyekanxFonts.variable} font-sans ss02`}
    >
      <body className={`${iranyekanxFonts.variable} font-sans ss02`}>
        <GlobalContextProvider>{children}</GlobalContextProvider>
      </body>
    </html>
  );
}
